# Generated by Django 5.2.3 on 2025-10-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'country'], name='environment_name_a6a5c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('aqi', models.IntegerField()),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_readings', to='environmental_monitor.city')),
            ],
            options={
                'verbose_name': 'Air Quality Reading',
                'verbose_name_plural': 'Air Quality Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', '-timestamp'], name='environment_city_id_ec4fbc_idx'), models.Index(fields=['-timestamp'], name='environment_timesta_5af154_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField(blank=True, null=True)),
                ('humidity', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('wind_direction', models.IntegerField(blank=True, null=True)),
                ('clouds', models.IntegerField(blank=True, null=True)),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('weather_main', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_readings', to='environmental_monitor.city')),
            ],
            options={
                'verbose_name': 'Weather Reading',
                'verbose_name_plural': 'Weather Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['city', '-timestamp'], name='environment_city_id_35d8d8_idx'), models.Index(fields=['-timestamp'], name='environment_timesta_d3f22e_idx')],
            },
        ),
    ]
