# Generated by Django 5.2.3 on 2025-10-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherreading',
            name='weather_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
