# Generated by Django 5.2.3 on 2025-10-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_monitor', '0002_weatherreading_weather_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherreading',
            name='weather_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
